apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: write-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: write-container
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
         claimName: task-pv-claim2
      containers:
      - name: write-container
        image: chkaushik/wrrepo
        volumeMounts:
        - mountPath: /data
          name: task-pv-storage
